/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.Napakalaki;

public class NapakalakiView extends javax.swing.JFrame{
    
    Napakalaki napakalakiModel;
    MonsterView monsterModel = new MonsterView();
    PlayerView playerModel = new PlayerView();
    
    public NapakalakiView(){
      initComponents();
      L_MonsterVIew.setVisible(false);
    }
    
    public void setNapakalaki(Napakalaki NapakalakiModel){
      napakalakiModel=NapakalakiModel;
      L_PlayerView.setPlayer(napakalakiModel.getCurrentPlayer());
      L_MonsterVIew.setMonster(napakalakiModel.getCurrentMonster());
      B_Combat.setVisible(false);
      B_NextTurn.setVisible(false);
      B_MTM.setVisible(true);
      repaint();
      revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_PlayerView = new GUI.PlayerView();
        B_NextTurn = new javax.swing.JButton();
        B_MTM = new javax.swing.JButton();
        B_Combat = new javax.swing.JButton();
        B_Exit = new javax.swing.JButton();
        L_MonsterVIew = new GUI.MonsterView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B_NextTurn.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        B_NextTurn.setForeground(new java.awt.Color(54, 69, 254));
        B_NextTurn.setText("Next Turn");
        B_NextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_NextTurnActionPerformed(evt);
            }
        });

        B_MTM.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        B_MTM.setForeground(new java.awt.Color(54, 69, 254));
        B_MTM.setText("Meet the monster!");
        B_MTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_MTMActionPerformed(evt);
            }
        });

        B_Combat.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        B_Combat.setForeground(new java.awt.Color(54, 69, 254));
        B_Combat.setText("Combat!");
        B_Combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CombatActionPerformed(evt);
            }
        });

        B_Exit.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        B_Exit.setText("Exit :(");
        B_Exit.setToolTipText("");
        B_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(L_PlayerView, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(L_MonsterVIew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_MTM)
                    .addComponent(B_NextTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(B_Combat)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(B_Exit)
                        .addGap(174, 174, 174))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_PlayerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(L_MonsterVIew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B_Combat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                        .addComponent(B_Exit))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(B_MTM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B_NextTurn)
                        .addContainerGap())))
        );

        L_PlayerView.getAccessibleContext().setAccessibleName("L_PlayerView");
        L_MonsterVIew.getAccessibleContext().setAccessibleName("L_MonsterVIew");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ExitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_B_ExitActionPerformed

  private void B_MTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MTMActionPerformed
    L_MonsterVIew.setMonster(napakalakiModel.getCurrentMonster());
    L_MonsterVIew.setVisible(true);
    B_MTM.setVisible(false);
    B_NextTurn.setVisible(false);
    B_Combat.setVisible(true);
    monsterModel.repaint();
  }//GEN-LAST:event_B_MTMActionPerformed

  private void B_CombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CombatActionPerformed
    //COMBATIR
    B_MTM.setVisible(false);
    B_Combat.setVisible(false);
    B_NextTurn.setVisible(true);
  }//GEN-LAST:event_B_CombatActionPerformed

  private void B_NextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_NextTurnActionPerformed
    L_MonsterVIew.setVisible(false);
    napakalakiModel.nextTurn();
    L_PlayerView.setPlayer(napakalakiModel.getCurrentPlayer());
    L_PlayerView.repaint();
    B_NextTurn.setVisible(false);
    B_MTM.setVisible(true);
    repaint();
  }//GEN-LAST:event_B_NextTurnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Combat;
    private javax.swing.JButton B_Exit;
    private javax.swing.JButton B_MTM;
    private javax.swing.JButton B_NextTurn;
    private GUI.MonsterView L_MonsterVIew;
    private GUI.PlayerView L_PlayerView;
    // End of variables declaration//GEN-END:variables
}
