/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.Napakalaki;

public class NapakalakiView extends javax.swing.JFrame{
    
    Napakalaki napakalakiModel;
    MonsterView monsterModel = new MonsterView();
    PlayerView playerModel = new PlayerView();
    
    public NapakalakiView(){
      initComponents();
      L_MonsterView.setVisible(false);
    }
    
    public void setNapakalaki(Napakalaki NapakalakiModel){
      napakalakiModel=NapakalakiModel;
      L_PlayerView.setPlayer(napakalakiModel.getCurrentPlayer());
      L_MonsterView.setMonster(napakalakiModel.getCurrentMonster());
      B_Combat.setVisible(false);
      B_NextTurn.setVisible(false);
      B_MTM.setVisible(true);
      repaint();
      revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    L_MonsterView = new GUI.MonsterView();
    L_PlayerView = new GUI.PlayerView();
    B_NextTurn = new javax.swing.JButton();
    B_MTM = new javax.swing.JButton();
    B_Combat = new javax.swing.JButton();
    B_Exit = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    B_NextTurn.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
    B_NextTurn.setForeground(new java.awt.Color(54, 69, 254));
    B_NextTurn.setText("Next Turn");
    B_NextTurn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B_NextTurnActionPerformed(evt);
      }
    });

    B_MTM.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
    B_MTM.setForeground(new java.awt.Color(54, 69, 254));
    B_MTM.setText("Meet the monster!");
    B_MTM.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B_MTMActionPerformed(evt);
      }
    });

    B_Combat.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
    B_Combat.setForeground(new java.awt.Color(54, 69, 254));
    B_Combat.setText("Combat!");
    B_Combat.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B_CombatActionPerformed(evt);
      }
    });

    B_Exit.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    B_Exit.setText("Exit :(");
    B_Exit.setToolTipText("");
    B_Exit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B_ExitActionPerformed(evt);
      }
    });

    jLabel1.setText("tds l0s derexs rebershadios");

    jLabel2.setText("hadry ( ͡° ͜ʖ ͡°) cerby");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(B_MTM, javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(B_NextTurn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_Combat))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_PlayerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(L_MonsterView, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 89, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(B_Exit)))
        .addContainerGap())
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(22, 22, 22)
          .addComponent(jLabel2)
          .addContainerGap(834, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(L_PlayerView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(L_MonsterView, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        .addGap(29, 29, 29)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addGroup(layout.createSequentialGroup()
            .addGap(2, 2, 2)
            .addComponent(B_MTM)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(B_NextTurn))
          .addComponent(B_Combat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(B_Exit)
            .addContainerGap())
          .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
          .addContainerGap(442, Short.MAX_VALUE)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(22, 22, 22)))
    );

    L_MonsterView.getAccessibleContext().setAccessibleName("L_MonsterView");
    L_PlayerView.getAccessibleContext().setAccessibleName("L_PlayerView");

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void B_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ExitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_B_ExitActionPerformed

  private void B_MTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MTMActionPerformed
    L_MonsterView.setMonster(napakalakiModel.getCurrentMonster());
    L_MonsterView.setVisible(true);
    B_MTM.setVisible(false);
    B_NextTurn.setVisible(false);
    B_Combat.setVisible(true);
    monsterModel.repaint();
  }//GEN-LAST:event_B_MTMActionPerformed

  private void B_CombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CombatActionPerformed
    //COMBATIR
    B_MTM.setVisible(false);
    B_Combat.setVisible(false);
    B_NextTurn.setVisible(true);
  }//GEN-LAST:event_B_CombatActionPerformed

  private void B_NextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_NextTurnActionPerformed
    napakalakiModel.nextTurn();
    L_PlayerView.setPlayer(napakalakiModel.getCurrentPlayer());
    L_PlayerView.repaint();
    B_NextTurn.setVisible(false);
    B_MTM.setVisible(true);
    repaint();
  }//GEN-LAST:event_B_NextTurnActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton B_Combat;
  private javax.swing.JButton B_Exit;
  private javax.swing.JButton B_MTM;
  private javax.swing.JButton B_NextTurn;
  private GUI.MonsterView L_MonsterView;
  private GUI.PlayerView L_PlayerView;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  // End of variables declaration//GEN-END:variables
}
