/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Player;
import NapakalakiGame.Treasure;
import NapakalakiGame.BadConsequence;
import NapakalakiGame.Napakalaki;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;


public class PlayerView extends javax.swing.JPanel{
    
    public Player playerModel;
    public BadConsequenceView badConsequenceModel=new BadConsequenceView();
    private Napakalaki napakalakiModel=Napakalaki.getInstance();
    
    public PlayerView(){
      initComponents();
    }
    
    public void setNapakalakiModel(Napakalaki n){
      this.napakalakiModel=n;
    }
    
    public Napakalaki getNapakalakiModel(){
      return napakalakiModel;
    }
    
    private ArrayList<Treasure> getSelectedTreasures(JPanel aPanel){
      TreasureView tv;
      ArrayList<Treasure> output = new ArrayList();
      for(Component c:aPanel.getComponents()){
        tv=(TreasureView) c;        // La vin vieo ke paranolla + wapa ase esto wajjja
        if(tv.isSelected())
          output.add(tv.getTreasure());
      }
      return output;
    }
    
    private void fillTreasurePanel(JPanel aPanel, ArrayList<Treasure> aList){
      aPanel.removeAll();
      for(Treasure t : aList){
        TreasureView aTreasureView = new TreasureView();
        aTreasureView.setTreasure(t);
        aTreasureView.setVisible(true);
        aPanel.add(aTreasureView);
      }
      aPanel.repaint();
      aPanel.revalidate();
    }
    
    public void setPlayer(Player p){
      playerModel=p;
      L_PlayerName.setText(playerModel.getName());
      L_PlayerLevel.setText(String.valueOf(playerModel.getLevels()));
      L_PlayerCombatLevel.setText(String.valueOf(playerModel.getCombatLevel()));
      L_PlayerEnemy.setText(String.valueOf(playerModel.getEnemy().getName()));
      this.fillTreasurePanel(P_VisibleTreasures, playerModel.getVisibleTreasures());
      this.fillTreasurePanel(P_HiddenTreasures, playerModel.getHiddenTreasures());
      BadConsequence bc=playerModel.getPendingBadConsequence();
      badConsequenceModel.setBadConsequence(bc);

      repaint();
      revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    L_PlayerName = new javax.swing.JLabel();
    L_PlayerCombatLevel = new javax.swing.JLabel();
    L_PlayerLevel = new javax.swing.JLabel();
    L_PlayerEnemy = new javax.swing.JLabel();
    P_VisibleTreasures = new javax.swing.JPanel();
    P_HiddenTreasures = new javax.swing.JPanel();
    B_StealTreasure = new javax.swing.JButton();
    B_DiscardTreasure = new javax.swing.JButton();
    B_MakeVisible = new javax.swing.JButton();
    B_DiscardAllTreasures = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();

    P_VisibleTreasures.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    P_VisibleTreasures.setLayout(null);

    P_HiddenTreasures.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    P_HiddenTreasures.setLayout(null);

    B_StealTreasure.setText("Steal Treasure");
    B_StealTreasure.setActionCommand("StealTreasure");
    B_StealTreasure.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B_StealTreasureActionPerformed(evt);
      }
    });

    B_DiscardTreasure.setText("Discard Treasure");
    B_DiscardTreasure.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B_DiscardTreasureActionPerformed(evt);
      }
    });

    B_MakeVisible.setText("Make Visible");
    B_MakeVisible.setToolTipText("");
    B_MakeVisible.setActionCommand("MakeVisible");
    B_MakeVisible.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B_MakeVisibleActionPerformed(evt);
      }
    });

    B_DiscardAllTreasures.setText("Discard All Treasures");
    B_DiscardAllTreasures.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B_DiscardAllTreasuresActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    jLabel1.setText("Name");

    jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    jLabel2.setText("Level");

    jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    jLabel3.setText("Combat level");

    jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    jLabel4.setText("Enemy's name");

    jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    jLabel5.setText("Visible Treasures");

    jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    jLabel6.setText("Hidden Treasures");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(L_PlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(L_PlayerLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(L_PlayerCombatLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(30, 30, 30))
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(B_StealTreasure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(B_DiscardTreasure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(54, 54, 54)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(B_MakeVisible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(B_DiscardAllTreasures, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(L_PlayerEnemy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addComponent(jLabel5)
          .addComponent(P_VisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6)
          .addComponent(P_HiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel1)
          .addComponent(L_PlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2)
          .addComponent(L_PlayerLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3)
          .addComponent(L_PlayerCombatLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel4)
          .addComponent(L_PlayerEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(P_VisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(P_HiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(B_StealTreasure, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(B_MakeVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(27, 27, 27)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(B_DiscardTreasure, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(B_DiscardAllTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    L_PlayerName.getAccessibleContext().setAccessibleName("L_PlayerCombatLevel");
    L_PlayerCombatLevel.getAccessibleContext().setAccessibleName("L_PlayerCombatLevel");
    L_PlayerLevel.getAccessibleContext().setAccessibleName("L_PlayerLevel");
    L_PlayerEnemy.getAccessibleContext().setAccessibleName("L_PlayerEnemy");
    P_VisibleTreasures.getAccessibleContext().setAccessibleName("visibleTreasures");
    P_HiddenTreasures.getAccessibleContext().setAccessibleName("hiddenTreasures");
    B_StealTreasure.getAccessibleContext().setAccessibleName("B_StealTreasure");
    B_DiscardTreasure.getAccessibleContext().setAccessibleName("B_DiscardTreasure");
    B_MakeVisible.getAccessibleContext().setAccessibleName("B_MakeVisible");
    B_DiscardAllTreasures.getAccessibleContext().setAccessibleName("B_DiscardAllTreasures");
  }// </editor-fold>//GEN-END:initComponents

    private void B_StealTreasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_StealTreasureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_StealTreasureActionPerformed

    private void B_MakeVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MakeVisibleActionPerformed
      ArrayList<Treasure> selHidden = this.getSelectedTreasures(P_HiddenTreasures);
      napakalakiModel.makeTreasureVisible(selHidden);
      setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_B_MakeVisibleActionPerformed

    private void B_DiscardTreasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DiscardTreasureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_DiscardTreasureActionPerformed

    private void B_DiscardAllTreasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DiscardAllTreasuresActionPerformed

    }//GEN-LAST:event_B_DiscardAllTreasuresActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton B_DiscardAllTreasures;
  private javax.swing.JButton B_DiscardTreasure;
  private javax.swing.JButton B_MakeVisible;
  private javax.swing.JButton B_StealTreasure;
  private javax.swing.JLabel L_PlayerCombatLevel;
  private javax.swing.JLabel L_PlayerEnemy;
  private javax.swing.JLabel L_PlayerLevel;
  private javax.swing.JLabel L_PlayerName;
  private javax.swing.JPanel P_HiddenTreasures;
  private javax.swing.JPanel P_VisibleTreasures;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  // End of variables declaration//GEN-END:variables
}
