/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Player;
import NapakalakiGame.Treasure;
import NapakalakiGame.BadConsequence;
import java.util.ArrayList;
import javax.swing.JPanel;


public class PlayerView extends javax.swing.JPanel{
    
    Player playerModel;
    BadConsequenceView badConsequenceModel;
    
    public PlayerView(){
      initComponents();
    }
    
    public void setPlayer(Player p){
      playerModel=p;
      this.fillTreasurePanel(visibleTreasures, playerModel.getVisibleTreasures());
      this.fillTreasurePanel(hiddenTreasures, playerModel.getHiddenTreasures());
      BadConsequence bc=p.getPendingBadConsequence();
      badConsequenceModel.setBadConsequence(bc);
      repaint();
      revalidate();
    }
    
    private void fillTreasurePanel(JPanel aPanel, ArrayList<Treasure> aList){
      aPanel.removeAll();
      for(Treasure t : aList){
        TreasureView aTreasureView = new TreasureView();
        aTreasureView.setTreasure(t);
        aTreasureView.setVisible(true);
        aPanel.add(aTreasureView);
      }
      aPanel.repaint();
      aPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    L_PlayerName = new javax.swing.JLabel();
    L_PlayerCombatLevel = new javax.swing.JLabel();
    L_PlayerLevel = new javax.swing.JLabel();
    L_PlayerEnemy = new javax.swing.JLabel();
    visibleTreasures = new javax.swing.JPanel();
    hiddenTreasures = new javax.swing.JPanel();
    B_StealTreasure = new javax.swing.JButton();
    B_DiscardTreasure = new javax.swing.JButton();
    B_MakeVisible = new javax.swing.JButton();
    B_DiscardAllTreasures = new javax.swing.JButton();
    badConsequenceView1 = new GUI.BadConsequenceView();

    visibleTreasures.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    hiddenTreasures.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    B_StealTreasure.setText("Steal Treasure");
    B_StealTreasure.setActionCommand("StealTreasure");
    B_StealTreasure.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B_StealTreasureActionPerformed(evt);
      }
    });

    B_DiscardTreasure.setText("Discard Treasure");
    B_DiscardTreasure.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B_DiscardTreasureActionPerformed(evt);
      }
    });

    B_MakeVisible.setText("Make Visible");
    B_MakeVisible.setToolTipText("");
    B_MakeVisible.setActionCommand("MakeVisible");
    B_MakeVisible.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B_MakeVisibleActionPerformed(evt);
      }
    });

    B_DiscardAllTreasures.setText("Discard All Treasures");
    B_DiscardAllTreasures.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B_DiscardAllTreasuresActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(36, 36, 36)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(badConsequenceView1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(B_StealTreasure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(visibleTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(L_PlayerEnemy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(L_PlayerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(hiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(B_DiscardTreasure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(54, 54, 54)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(B_MakeVisible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(L_PlayerLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(B_DiscardAllTreasures, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(56, 56, 56)
            .addComponent(L_PlayerCombatLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(36, 36, 36)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(L_PlayerLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(L_PlayerCombatLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(L_PlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(L_PlayerEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(visibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(hiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(33, 33, 33)
        .addComponent(badConsequenceView1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(B_StealTreasure, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(B_MakeVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(27, 27, 27)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(B_DiscardTreasure, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(B_DiscardAllTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    L_PlayerName.getAccessibleContext().setAccessibleName("L_PlayerName");
    L_PlayerCombatLevel.getAccessibleContext().setAccessibleName("L_PlayerCombatLevel");
    L_PlayerLevel.getAccessibleContext().setAccessibleName("L_PlayerLevel");
    L_PlayerEnemy.getAccessibleContext().setAccessibleName("L_PlayerEnemy");
    visibleTreasures.getAccessibleContext().setAccessibleName("visibleTreasures");
    hiddenTreasures.getAccessibleContext().setAccessibleName("hiddenTreasures");
    B_StealTreasure.getAccessibleContext().setAccessibleName("B_StealTreasure");
    B_DiscardTreasure.getAccessibleContext().setAccessibleName("B_DiscardTreasure");
    B_MakeVisible.getAccessibleContext().setAccessibleName("B_MakeVisible");
    B_DiscardAllTreasures.getAccessibleContext().setAccessibleName("B_DiscardAllTreasures");
  }// </editor-fold>//GEN-END:initComponents

    private void B_StealTreasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_StealTreasureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_StealTreasureActionPerformed

    private void B_MakeVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MakeVisibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_MakeVisibleActionPerformed

    private void B_DiscardTreasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DiscardTreasureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_DiscardTreasureActionPerformed

    private void B_DiscardAllTreasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DiscardAllTreasuresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_DiscardAllTreasuresActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton B_DiscardAllTreasures;
  private javax.swing.JButton B_DiscardTreasure;
  private javax.swing.JButton B_MakeVisible;
  private javax.swing.JButton B_StealTreasure;
  private javax.swing.JLabel L_PlayerCombatLevel;
  private javax.swing.JLabel L_PlayerEnemy;
  private javax.swing.JLabel L_PlayerLevel;
  private javax.swing.JLabel L_PlayerName;
  private GUI.BadConsequenceView badConsequenceView1;
  private javax.swing.JPanel hiddenTreasures;
  private javax.swing.JPanel visibleTreasures;
  // End of variables declaration//GEN-END:variables
}
