/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Treasure;

public class TreasureView extends javax.swing.JPanel{
    
    Treasure treasureModel;
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
      initComponents();
    }

    public void setTreasure(Treasure T){
      treasureModel=T;
      repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_IMG_Treasure = new javax.swing.JLabel();
        L_TreasureType = new javax.swing.JLabel();
        L_TreasureName = new javax.swing.JLabel();
        L_TreasureBonus = new javax.swing.JLabel();

        L_IMG_Treasure.setName("L_IMG_Treasure"); // NOI18N

        L_TreasureType.setName("L_TreasureType"); // NOI18N

        L_TreasureName.setName("L_TreasureName"); // NOI18N

        L_TreasureBonus.setName("L_TreasureBonus"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_TreasureType, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_TreasureBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_TreasureName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(L_IMG_Treasure, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(L_IMG_Treasure, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L_TreasureName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(L_TreasureBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(L_TreasureType, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );

        L_TreasureType.getAccessibleContext().setAccessibleName("L_TreasureType");
        L_TreasureName.getAccessibleContext().setAccessibleName("L_TreasureName");
        L_TreasureName.getAccessibleContext().setAccessibleDescription("");
        L_TreasureBonus.getAccessibleContext().setAccessibleName("L_TreasureBonus");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_IMG_Treasure;
    private javax.swing.JLabel L_TreasureBonus;
    private javax.swing.JLabel L_TreasureName;
    private javax.swing.JLabel L_TreasureType;
    // End of variables declaration//GEN-END:variables
}
