
package GUI;

import NapakalakiGame.Treasure;
import java.awt.Color;

public class TreasureView extends javax.swing.JPanel{
    
    Treasure treasureModel;
    boolean selected=false;
    
    public TreasureView(){
      initComponents();
    }

    public void setTreasure(Treasure T){
      treasureModel=T;
      L_TreasureBonus.setText(String.valueOf(treasureModel.getBonus()));
      L_TreasureName.setText(treasureModel.getName());
      L_TreasureType.setText(String.valueOf(treasureModel.getType()));
      repaint();
      revalidate();
    }
    
    public Treasure getTreasure(){
      return treasureModel;
    }
    
    public boolean isSelected(){
      return selected;
    }
    
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    L_TreasureName = new javax.swing.JLabel();
    L_TreasureBonus = new javax.swing.JLabel();
    L_TreasureType = new javax.swing.JLabel();

    addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        formMouseClicked(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    jLabel1.setText("Name");

    jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    jLabel2.setText("Bonus");

    jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
    jLabel3.setText("Type");

    L_TreasureName.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N

    L_TreasureBonus.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N

    L_TreasureType.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(L_TreasureType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(L_TreasureBonus, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
          .addComponent(L_TreasureName, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(L_TreasureName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(L_TreasureBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(L_TreasureType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    L_TreasureName.getAccessibleContext().setAccessibleName("L_TreasureName");
    L_TreasureBonus.getAccessibleContext().setAccessibleName("L_TreasureBonus");
    L_TreasureType.getAccessibleContext().setAccessibleName("L_TreasureType");
  }// </editor-fold>//GEN-END:initComponents

  private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    if(selected){
      selected=false;
      this.setBackground(Color.cyan);
    }
    else{
      selected=true;
      this.setBackground(Color.lightGray);
    }
    this.setOpaque(selected);
    repaint();
  }//GEN-LAST:event_formMouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel L_TreasureBonus;
  private javax.swing.JLabel L_TreasureName;
  private javax.swing.JLabel L_TreasureType;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  // End of variables declaration//GEN-END:variables
}
